stages:
  - build
  - test
  - docker

#global variables
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  APP_IMAGE: "$CI_REGISTRY_IMAGE/api-app:$CI_COMMIT_SHORT_SHA"
  APP_IMAGE_LATEST: "$CI_REGISTRY_IMAGE/api-app:latest"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository

#STAGE1 — BUILD
maven-build:
  stage: build
  image: maven:3.9-eclipse-temurin-21
  script:
    - echo "Building project..."
    - mvn -pl app package -am -DskipTests -q
  artifacts:
    paths:
      - app/target/*.jar
    expire_in: 1 hour

#STAGE 2 — TEST
maven-test:
  stage: test
  image: maven:3.9-eclipse-temurin-21
  services:
    - docker:27-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Running tests..."
    - mvn -pl app test -am
  artifacts:
    when: always
    reports:
      junit: app/target/surefire-reports/TEST-*.xml
    expire_in: 1 week

#STAGE 3 — DOCKER-BUILD
#runs on branches main and dev
docker-build:
  stage: docker
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "Logging in to GitLab Container Registry..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - echo "Building Docker image..."
    - docker build -t "$APP_IMAGE" -t "$APP_IMAGE_LATEST" .
    - echo "Pushing image to registry..."
    - docker push "$APP_IMAGE"
    - docker push "$APP_IMAGE_LATEST"
  only:
    - main
    - develop
    - dev
    - feature/ci-pipeline
